# Define Docker Compose version.
version: "3"

# Define all the containers.
services:
  # Frontend Container.
  dev:
    container_name: dev
    build: ./
    volumes:
      - ./octopod:/usr/src/app
    ports:
     - 4200:4200
    environment:
      NODE_ENV: development
    command: /usr/src/app/entrypoint.sh