version: "3"
services:
  dev:
    container_name: dev
    build: .
    ports:
      - "4200:4200"
    environment:
      SHELL: /bin/bash
      NODE_ENV: development
    volumes:
      - ~/.gitconfig:/etc/gitconfig
      - ./app:/usr/src/app
    command: /usr/src/app/entrypoint.sh
